/*
 * Stud_Client.java
 *
 * Created on August 1, 2006, 5:30 PM
 */
package Client;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.net.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author  Uday
 */

public class Stud_Client extends javax.swing.JFrame
{
    boolean ExpFlag;
    Connection db_conn;
    Socket serv;
    BufferedReader in ;
    PrintStream out;
    String data,ack;
    String IP;
    
    
    /** Creates new form Stud_Client */
    public Stud_Client()
    {
	IP="192.168.35.240";
	try
	{
	    serv= new Socket(IP,2108);
	    //serv_mesg = new BufferedReader(new InputStreamReader(System.in ));
	    in = new BufferedReader(new InputStreamReader(serv.getInputStream()));
	    out = new PrintStream(serv.getOutputStream());
	    //this.start();
	    System.out.println("Client detected server. Client server connected");
	}
	catch(Exception e)
	{
	    ExpFlag=true;
	    System.out.println("Socket error on client ");
	    System.out.println(e);
	}
	initComponents();
	Display.setVisible(false);
	chkcomp.setVisible(false);
	txtcomp.setVisible(false);
	this.setVisible(true);
	if(ExpFlag==true)
	{
	    jDialog2.setSize(500,150);
	    jDialog2.setVisible(true);
	    ExpFlag=false;
	}
	
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jDialog1 = new javax.swing.JDialog();
        //jDialog1.setSize(300,150);
        jButton3 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog2 = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        IPaddr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        InsertPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PersonalInsert = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobranch = new javax.swing.JComboBox();
        comboclass = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combodiv = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        roll_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paddr = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        pph = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        laddr = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        lph = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sesscmb = new javax.swing.JComboBox();
        chkcomp = new javax.swing.JCheckBox();
        txtcomp = new javax.swing.JTextField();
        txtdate = new javax.swing.JComboBox();
        txtmonth = new javax.swing.JComboBox();
        txtyear = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        Display = new javax.swing.JButton();
        AcademicsInsert = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtssc = new javax.swing.JTextField();
        chkhsc = new javax.swing.JRadioButton();
        chkdip = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txthsc = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtfe1 = new javax.swing.JTextField();
        txtse1 = new javax.swing.JTextField();
        txtte1 = new javax.swing.JTextField();
        txtbe1 = new javax.swing.JTextField();
        txtfe2 = new javax.swing.JTextField();
        txtse2 = new javax.swing.JTextField();
        txtte2 = new javax.swing.JTextField();
        txtbe2 = new javax.swing.JTextField();
        chkkt = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        ExtraInsert = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtproj = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ext_acad = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        ext_curr = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        InsertMenuItem = new javax.swing.JMenuItem();
        DisplayMenuItem = new javax.swing.JMenuItem();
        RefreshMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        jDialog1.setTitle("Information");
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jDialog1.setSize(366,120);
        jDialog1.setLocation(329,324);
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("ERROR");
        jLabel50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .add(jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel50, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                    .add(jDialog1Layout.createSequentialGroup()
                        .add(138, 138, 138)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel50)
                .add(15, 15, 15)
                .add(jButton3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2.setTitle("Information");
        jDialog2.setResizable(false);
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel31.setText("Enter Server IP/ Server Name");

        IPaddr.setFont(new java.awt.Font("Tahoma", 0, 14));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDialog2Layout = new org.jdesktop.layout.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog2Layout.createSequentialGroup()
                .add(jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jDialog2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel31))
                    .add(jDialog2Layout.createSequentialGroup()
                        .add(95, 95, 95)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(IPaddr, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDialog2Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(IPaddr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel31))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(jDialog2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton4))
                .addContainerGap())
        );

        getContentPane().setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Placement Organizer");
        setExtendedState(6);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                close_win(evt);
            }
        });

        InsertPanel.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                InsertPanelFocusGained(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1000, 600));
        PersonalInsert.setEnabled(false);
        PersonalInsert.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel1.setText("Branch *");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel5.setText("Class *");

        combobranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E&TC", "CIVIL", "MECHINCAL", "CHEMICAL", "COMPUTER", "IT", "PRODUCTION" }));

        comboclass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "T.E.", "B.E." }));
        comboclass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                comboclassActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel6.setText("Session *");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel8.setText("Div *");

        combodiv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel9.setText("Roll No. *");

        roll_no.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                roll_noFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                roll_noFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel10.setText("Name");

        fname.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fnameActionPerformed(evt);
            }
        });
        fname.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                fnameFocusLost(evt);
            }
        });

        lname.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                lnameFocusLost(evt);
            }
        });

        mname.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                mnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                mnameFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel11.setText("First *");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel12.setText("Middle");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel13.setText("Surname *");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel14.setText("Permenant");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel15.setText("Address *");

        paddr.setColumns(20);
        paddr.setRows(5);
        paddr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                paddrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                paddrFocusLost(evt);
            }
        });

        jScrollPane1.setViewportView(paddr);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel16.setText("Phone *");

        pph.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                pphFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                pphFocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel17.setText("eg : 020 - 24163607");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel18.setText("Local");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel19.setText("Address");

        laddr.setColumns(20);
        laddr.setRows(5);
        laddr.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                laddrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                laddrFocusLost(evt);
            }
        });

        jScrollPane2.setViewportView(laddr);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel20.setText("Phone ");

        lph.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                lphFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                lphFocusLost(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel21.setText("eg : 020 - 24163607");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel22.setText("E-Mail *");

        mail.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                mailFocusLost(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel23.setText("DOB *");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel24.setText("dd / mm / yyyy");

        sesscmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2005-06", "2006-07", "2007-08", "2008-09", "2009-10" }));

        chkcomp.setFont(new java.awt.Font("Times New Roman", 0, 18));
        chkcomp.setText("Company Joined?");
        chkcomp.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkcomp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        chkcomp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkcompActionPerformed(evt);
            }
        });

        txtdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        txtmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        txtyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));

        jLabel48.setText("Note 1 : Fields marked * are compulsory");

        Display.setText("Display Record");
        Display.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DisplayActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout PersonalInsertLayout = new org.jdesktop.layout.GroupLayout(PersonalInsert);
        PersonalInsert.setLayout(PersonalInsertLayout);
        PersonalInsertLayout.setHorizontalGroup(
            PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PersonalInsertLayout.createSequentialGroup()
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(886, 886, 886)
                        .add(jLabel7))
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 307, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(PersonalInsertLayout.createSequentialGroup()
                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(PersonalInsertLayout.createSequentialGroup()
                                        .add(73, 73, 73)
                                        .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(135, 135, 135)
                                        .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(159, 159, 159)
                                        .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jLabel24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PersonalInsertLayout.createSequentialGroup()
                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, PersonalInsertLayout.createSequentialGroup()
                                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(combobranch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(combodiv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(fname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(mname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(PersonalInsertLayout.createSequentialGroup()
                                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                            .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .add(14, 14, 14)
                                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                            .add(comboclass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                            .add(roll_no, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(PersonalInsertLayout.createSequentialGroup()
                                                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(sesscmb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(lname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .add(Display, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(lph, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(PersonalInsertLayout.createSequentialGroup()
                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(mail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(PersonalInsertLayout.createSequentialGroup()
                                                .add(txtdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(txtmonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(txtyear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(278, 278, 278)
                                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(txtcomp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(chkcomp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                            .add(PersonalInsertLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(pph, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        PersonalInsertLayout.setVerticalGroup(
            PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PersonalInsertLayout.createSequentialGroup()
                .add(23, 23, 23)
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(comboclass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(PersonalInsertLayout.createSequentialGroup()
                            .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel1)
                                .add(combobranch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(sesscmb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(18, 18, 18))
                        .add(PersonalInsertLayout.createSequentialGroup()
                            .add(jLabel5)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))))
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(roll_no, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .add(Display))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, combodiv, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel10)
                    .add(fname)
                    .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(mname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .add(lname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PersonalInsertLayout.createSequentialGroup()
                                .add(jLabel14)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel15))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel16)
                            .add(pph, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel13))
                .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PersonalInsertLayout.createSequentialGroup()
                                .add(jLabel18)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel19))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(21, 21, 21)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel20)
                            .add(lph, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(7, 7, 7)
                        .add(jLabel21)
                        .add(4, 4, 4)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel22)
                            .add(mail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(14, 14, 14)
                        .add(PersonalInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel23)
                            .add(txtcomp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtmonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtyear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel24)
                        .add(36, 36, 36)
                        .add(jLabel48)
                        .add(77, 77, 77)
                        .add(jLabel7))
                    .add(PersonalInsertLayout.createSequentialGroup()
                        .add(163, 163, 163)
                        .add(chkcomp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        jTabbedPane1.addTab("Personal", PersonalInsert);

        AcademicsInsert.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel2.setText("ENTER MARKS (PERCENTAGE)");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel3.setText("SSC *");

        txtssc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtsscActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkhsc);
        chkhsc.setFont(new java.awt.Font("Times New Roman", 0, 18));
        chkhsc.setText("HSC");
        chkhsc.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkhsc.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(chkdip);
        chkdip.setFont(new java.awt.Font("Times New Roman", 0, 18));
        chkdip.setText("DIPLOMA");
        chkdip.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkdip.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel4.setText("SELECT");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel25.setText("HSC /DIPLOMA *");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel26.setText("HSC /DIPLOMA *");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel27.setText("F.E. SEMESTER I **");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel28.setText("S.E. SEMESTER I *");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel29.setText("T.E. SEMESTER I *");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel30.setText("B.E. SEMESTER I");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel40.setText("F.E. SEMESTER II  **");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel41.setText("S.E. SEMESTER II *");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel42.setText("T.E. SEMESTER II");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel43.setText("B.E. SEMESTER II");

        chkkt.setFont(new java.awt.Font("Times New Roman", 0, 18));
        chkkt.setText("ANY LIVE KT's ?");
        chkkt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        chkkt.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel33.setText("Note 1 : Fields marked * are compulsory");

        jLabel47.setText("Note 1 : Fields marked ** are not compulsory for Direct SE (Diploma) admissions");

        org.jdesktop.layout.GroupLayout AcademicsInsertLayout = new org.jdesktop.layout.GroupLayout(AcademicsInsert);
        AcademicsInsert.setLayout(AcademicsInsertLayout);
        AcademicsInsertLayout.setHorizontalGroup(
            AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(AcademicsInsertLayout.createSequentialGroup()
                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(AcademicsInsertLayout.createSequentialGroup()
                        .add(226, 226, 226)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 294, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(AcademicsInsertLayout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(AcademicsInsertLayout.createSequentialGroup()
                                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(chkkt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 181, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel28, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .add(jLabel4)
                                            .add(jLabel25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel27, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                        .add(jLabel30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 173, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jLabel33))
                                .add(56, 56, 56)
                                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(AcademicsInsertLayout.createSequentialGroup()
                                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(txtfe1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtse1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtte1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtbe1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(137, 137, 137)
                                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel43)
                                            .add(jLabel42)
                                            .add(jLabel41)
                                            .add(jLabel40))
                                        .add(96, 96, 96)
                                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(txtse2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtfe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtte2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(txtbe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(chkhsc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(txtssc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(chkdip)
                                    .add(txthsc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(AcademicsInsertLayout.createSequentialGroup()
                                .add(jLabel47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 397, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))))
                .add(113, 113, 113))
        );
        AcademicsInsertLayout.setVerticalGroup(
            AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(AcademicsInsertLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(AcademicsInsertLayout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtssc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(36, 36, 36)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(chkhsc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel25)
                            .add(chkdip))
                        .add(26, 26, 26)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel26)
                            .add(txthsc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(24, 24, 24)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel27)
                            .add(txtfe1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel28)
                            .add(txtse1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(26, 26, 26)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtte1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel29))
                        .add(26, 26, 26)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel30)
                            .add(txtbe1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(49, 49, 49)
                        .add(chkkt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(AcademicsInsertLayout.createSequentialGroup()
                        .add(234, 234, 234)
                        .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(AcademicsInsertLayout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel41)
                                    .add(txtse2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(26, 26, 26)
                                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(txtte2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel42))
                                .add(26, 26, 26)
                                .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel43)
                                    .add(txtbe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(AcademicsInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(txtfe2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel40)))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel33)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel47)
                .add(215, 215, 215))
        );
        jTabbedPane1.addTab("Academics", AcademicsInsert);

        ExtraInsert.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel32.setText("Projects");

        txtproj.setColumns(20);
        txtproj.setLineWrap(true);
        txtproj.setRows(5);
        txtproj.setWrapStyleWord(true);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel34.setText("Maximun 300 Characters");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel35.setText("Extra");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel36.setText("Academic");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel37.setText("Activities");

        ext_acad.setColumns(20);
        ext_acad.setLineWrap(true);
        ext_acad.setRows(5);
        ext_acad.setWrapStyleWord(true);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel38.setText("Maximum 200 characters. Information like vocational training, seminars, languages known etc.");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel39.setText("Extra");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel44.setText("Curricular");

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel45.setText("Activities");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 2, 14));
        jLabel46.setText("Maximun 200 Characters");

        ext_curr.setColumns(20);
        ext_curr.setLineWrap(true);
        ext_curr.setRows(5);
        ext_curr.setWrapStyleWord(true);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout ExtraInsertLayout = new org.jdesktop.layout.GroupLayout(ExtraInsert);
        ExtraInsert.setLayout(ExtraInsertLayout);
        ExtraInsertLayout.setHorizontalGroup(
            ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ExtraInsertLayout.createSequentialGroup()
                .addContainerGap()
                .add(ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .add(ExtraInsertLayout.createSequentialGroup()
                        .add(ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel44)
                            .add(jLabel45, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(jLabel39)
                            .add(jLabel37, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .add(jLabel36)
                            .add(jLabel35)
                            .add(jLabel32))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 555, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ext_acad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                            .add(txtproj)
                            .add(ext_curr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 853, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(66, 66, 66))
        );
        ExtraInsertLayout.setVerticalGroup(
            ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ExtraInsertLayout.createSequentialGroup()
                .addContainerGap()
                .add(ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel32)
                    .add(txtproj, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel34)
                .add(22, 22, 22)
                .add(ExtraInsertLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ExtraInsertLayout.createSequentialGroup()
                        .add(ext_acad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel38)
                        .add(34, 34, 34)
                        .add(ext_curr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel46))
                    .add(ExtraInsertLayout.createSequentialGroup()
                        .add(jLabel35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel36)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel37)
                        .add(116, 116, 116)
                        .add(jLabel39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel45)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel44)))
                .add(37, 37, 37)
                .add(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jTabbedPane1.addTab("Extra", ExtraInsert);

        org.jdesktop.layout.GroupLayout InsertPanelLayout = new org.jdesktop.layout.GroupLayout(InsertPanel);
        InsertPanel.setLayout(InsertPanelLayout);
        InsertPanelLayout.setHorizontalGroup(
            InsertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, InsertPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 982, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        InsertPanelLayout.setVerticalGroup(
            InsertPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, InsertPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 663, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        getContentPane().add(InsertPanel, "insert");

        jMenu1.setText("Form Option");
        jMenu1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenu1ActionPerformed(evt);
            }
        });

        InsertMenuItem.setText("Insert Record");
        InsertMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                InsertMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(InsertMenuItem);

        DisplayMenuItem.setText("Display Record");
        DisplayMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DisplayMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(DisplayMenuItem);

        RefreshMenuItem.setText("Refresh Form");
        RefreshMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RefreshMenuItemActionPerformed(evt);
            }
        });

        jMenu1.add(RefreshMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Connection");
        jMenu2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Set Server IP");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        Help.setText("Help");
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AboutActionPerformed(evt);
            }
        });

        Help.add(About);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void AboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AboutActionPerformed
    {//GEN-HEADEREND:event_AboutActionPerformed
        ImageIcon icon = new ImageIcon("Icon1.gif");
        
        JOptionPane.showMessageDialog(null,"This software has been developed by\nUday Pant, Gaurav Raka, " +
                "Sameer Kulkarni, Indira Pai.\n\n© lies with the above.","About",JOptionPane.INFORMATION_MESSAGE,icon);
    }//GEN-LAST:event_AboutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void InsertMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_InsertMenuItemActionPerformed
    {//GEN-HEADEREND:event_InsertMenuItemActionPerformed
	jButton1.setVisible(true);	
	Display.setVisible(false);
	chkcomp.setVisible(false);
	txtcomp.setVisible(false);
	
	fname.setEnabled(true);
	mname.setEnabled(true);
	lname.setEnabled(true);
	paddr.setEnabled(true);
	pph.setEnabled(true);
	laddr.setEnabled(true);
	lph.setEnabled(true);
	mail.setEnabled(true);
	txtdate.setEnabled(true);
	txtmonth.setEnabled(true);
	txtyear.setEnabled(true);	
	
	txtssc.setEnabled(true);
	txthsc.setEnabled(true);
	chkdip.setSelected(false);
	chkdip.setEnabled(true);
	chkhsc.setSelected(false);
	chkhsc.setEnabled(true);
	txtfe1.setEnabled(true);
	txtfe2.setEnabled(true);
	txtse1.setEnabled(true);
	txtse2.setEnabled(true);
	txtte1.setEnabled(true);
	txtte2.setEnabled(true);
	txtbe1.setEnabled(true);
	txtbe2.setEnabled(true);
	chkkt.setEnabled(true);
	chkkt.setSelected(false);
	
	txtproj.setEnabled(true);
	ext_acad.setEnabled(true);
	ext_curr.setEnabled(true);
	
	reset();
    }//GEN-LAST:event_InsertMenuItemActionPerformed
    
    private void DisplayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DisplayActionPerformed
    {//GEN-HEADEREND:event_DisplayActionPerformed
	String RollNo=null;
	int KeySize=5;
	/* ROLL NO GENERATION */
	if(comboclass.getSelectedIndex()==0)
	    RollNo="T";
	if(comboclass.getSelectedIndex()==1)
	    RollNo="B";
	
	RollNo+=combobranch.getSelectedIndex()+1;
	RollNo+=combodiv.getSelectedIndex();
	
	String Num=roll_no.getText();
	if(Num.length()==1)
	    Num="0"+Num;
	RollNo+=Num;
	String Sess = "" + ((String)sesscmb.getSelectedItem()).charAt(2) + ((String)sesscmb.getSelectedItem()).charAt(3) + ((String)sesscmb.getSelectedItem()).charAt(5) + ((String)sesscmb.getSelectedItem()).charAt(6);
	String SelQuery = "select:" + RollNo + ":" + Sess;
	System.out.println(SelQuery);
	char []QueryToSend = EncryptString(SelQuery,KeySize);
	System.out.println(QueryToSend);
	out.println(QueryToSend);
	
	CopyFunction(RollNo,Sess);
    }//GEN-LAST:event_DisplayActionPerformed
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	IP=IPaddr.getText();
	try
	{
	    serv= new Socket(IP,2108);
	    //serv_mesg = new BufferedReader(new InputStreamReader(System.in ));
	    in = new BufferedReader(new InputStreamReader(serv.getInputStream()));
	    out = new PrintStream(serv.getOutputStream());
	    //this.start();
	    System.out.println("Client detected server. Client server connected");
	    jDialog2.setVisible(false);
	}
	catch(Exception e)
	{
	    System.out.println("Socket error on client ");
	    System.out.println(e);
	/*    jDialog2 = new javax.swing.JDialog();
	    IP="192.168.1.2";
	    jDialog2.setSize(500,150);
	    jDialog2.setVisible(true);
	    IP=IPaddr.getText();
	    new Stud_Client().setVisible(true);*/
	    
	}
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void DisplayMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DisplayMenuItemActionPerformed
    {//GEN-HEADEREND:event_DisplayMenuItemActionPerformed
	jButton1.setVisible(false);
	Display.setVisible(true);
	chkcomp.setVisible(true);
	txtcomp.setVisible(true);
	
	fname.setEnabled(false);
	mname.setEnabled(false);
	lname.setEnabled(false);
	paddr.setEnabled(false);
	pph.setEnabled(false);
	laddr.setEnabled(false);
	lph.setEnabled(false);
	mail.setEnabled(false);
	txtdate.setEnabled(false);
	txtmonth.setEnabled(false);
	txtyear.setEnabled(false);
	chkcomp.setEnabled(false);
	txtcomp.setEnabled(false);
	
	txtssc.setEnabled(false);
	txthsc.setEnabled(false);
	chkdip.setSelected(false);
	chkdip.setEnabled(false);
	chkhsc.setSelected(false);
	chkhsc.setEnabled(false);
	txtfe1.setEnabled(false);
	txtfe2.setEnabled(false);
	txtse1.setEnabled(false);
	txtse2.setEnabled(false);
	txtte1.setEnabled(false);
	txtte2.setEnabled(false);
	txtbe1.setEnabled(false);
	txtbe2.setEnabled(false);
	chkkt.setEnabled(false);
	chkkt.setSelected(false);
	
	txtproj.setEnabled(false);
	ext_acad.setEnabled(false);
	ext_curr.setEnabled(false);
    }//GEN-LAST:event_DisplayMenuItemActionPerformed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
	jDialog2.setSize(500,150);
	jDialog2.setVisible(true);
	IP=IPaddr.getText();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void RefreshMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RefreshMenuItemActionPerformed
    {//GEN-HEADEREND:event_RefreshMenuItemActionPerformed
	reset();
    }//GEN-LAST:event_RefreshMenuItemActionPerformed
    
    void reset()
    {
        chkcomp.setSelected(false);
        txtcomp.setEnabled(false);
        chkdip.setSelected(false);
        chkhsc.setSelected(false);
        chkkt.setSelected(false);

        combobranch.setEnabled(true);
        combodiv.setEnabled(true);
        comboclass.setEnabled(true);
        sesscmb.setEnabled(true);
        roll_no.setEnabled(true);

        combobranch.setSelectedIndex(0);
        combodiv.setSelectedIndex(0);
        comboclass.setSelectedIndex(0);
        sesscmb.setSelectedIndex(0);
        txtdate.setSelectedIndex(0);
        txtmonth.setSelectedIndex(0);
        txtyear.setSelectedIndex(0);
        
        ext_acad.setText("");
        ext_curr.setText("");
        fname.setText("");
        laddr.setText("");
        lname.setText("");
        lph.setText("");
        mail.setText("");
        mname.setText("");
        paddr.setText("");
        pph.setText("");
        roll_no.setText("");

        txtbe1.setText("");
        txtbe2.setText("");
        txtcomp.setText("");

        txtfe1.setText("");
        txtfe2.setText("");
        txthsc.setText("");

        txtproj.setText("");
        txtse1.setText("");
        txtse2.setText("");
        txtssc.setText("");
        txtte1.setText("");
        txtte2.setText("");
        jTabbedPane1.setSelectedIndex(0);
    }
    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
	
    }//GEN-LAST:event_jMenu1ActionPerformed
    
    private void close_win(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close_win
// TODO add your handling code here:
	
	try
	{
	    String cls="close";
	    char Input1[]=new char[cls.length()];
	    char Output1[]=new char[cls.length()];
	    Input1=cls.toCharArray();
	    int KeySize=5;
	    for(int z=0;z<cls.length();z++)
	    {
		if((Input1[z]>='a'&&Input1[z]<='z')||(Input1[z]>='A'&&Input1[z]<='Z'))
		    Output1[z]=Encrypt(Input1[z],KeySize);
		else
		    Output1[z]=Input1[z];
	    }
	    out.println(Output1);
	}
	catch(Exception e)
	{
	    e.printStackTrace();
	}
	System.out.println("close");
    }//GEN-LAST:event_close_win
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
	jDialog1.setVisible(false);
	jDialog1.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void InsertPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InsertPanelFocusGained
	
    }//GEN-LAST:event_InsertPanelFocusGained
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	
	float avg=0;
	int TotSems=0;
	String RollNo=null;
	/* ROLL NO GENERATION */
	if(comboclass.getSelectedIndex()==0)
	    RollNo="T";
	if(comboclass.getSelectedIndex()==1)
	    RollNo="B";
	
	RollNo+=combobranch.getSelectedIndex()+1;
	RollNo+=combodiv.getSelectedIndex();
	
	String Num=roll_no.getText();
	if(Num.length()==1)
	    Num="0"+Num;
	RollNo+=Num;
	
	System.out.println(RollNo);
	
	if(roll_no.getText().equals(""))
	{
	    PersonalInsert.requestFocus();
	    roll_no.requestFocus();
	    jLabel50.setText("Error : Roll Number not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	if(fname.getText().equals(""))
	{
	    jLabel50.setText("Error : First Name not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	else if(lname.getText().equals(""))
	{
	    jLabel50.setText("Error : Last Name not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	else if(paddr.getText().equals(""))
	{
	    jLabel50.setText("Error : Permanenet Address not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	else if(pph.getText().equals(""))
	{
	    jLabel50.setText("Error : Phone No not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	    
	}
	
	else if(mail.getText().equals(""))
	{
	    jLabel50.setText("Error : Email Id not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	else if(Integer.parseInt(txtmonth.getSelectedItem().toString())==2)
	{
	    if(Integer.parseInt(txtyear.getSelectedItem().toString())%4==0)
	    {
		if(Integer.parseInt(txtdate.getSelectedItem().toString())>29)
		{
		    jLabel50.setText("Error : DATE is incorrect");
		    jDialog1.repaint();
		    jDialog1.setVisible(true);
		    return;
		}
	    }
	    else
	    {
		if(Integer.parseInt(txtdate.getSelectedItem().toString())>28)
		{
		    jLabel50.setText("Error : DATE is incorrect");
		    jDialog1.repaint();
		    jDialog1.setVisible(true);
		    return;
		}
	    }
	}
	
	else if(Integer.parseInt(txtmonth.getSelectedItem().toString())==1 || Integer.parseInt(txtmonth.getSelectedItem().toString())==3 || Integer.parseInt(txtmonth.getSelectedItem().toString())==5 || Integer.parseInt(txtmonth.getSelectedItem().toString())==7 || Integer.parseInt(txtmonth.getSelectedItem().toString())==8 || Integer.parseInt(txtmonth.getSelectedItem().toString())==10 || Integer.parseInt(txtmonth.getSelectedItem().toString())==12)
	{
	    if(Integer.parseInt(txtdate.getSelectedItem().toString())>31)
	    {
		jLabel50.setText("Error : DATE is incorrect");
		jDialog1.repaint();
		jDialog1.setVisible(true);
		return;
	    }
	}
	
	else if(Integer.parseInt(txtmonth.getSelectedItem().toString())==4 || Integer.parseInt(txtmonth.getSelectedItem().toString())==6 || Integer.parseInt(txtmonth.getSelectedItem().toString())==9 || Integer.parseInt(txtmonth.getSelectedItem().toString())==11)
	{
	    if(Integer.parseInt(txtdate.getSelectedItem().toString())>30)
	    {
		jLabel50.setText("Error : DATE is incorrect");
		jDialog1.repaint();
		jDialog1.setVisible(true);
		return;
	    }
	}
	
	if(!chkcomp.isSelected())
	    txtcomp.setText("");
	
	else
	{
	    if(txtcomp.getText().equals(""))
	    {
		jLabel50.setText("Error : Company Name not entered");
		jDialog1.repaint();
		jDialog1.setVisible(true);
		return;
	    }
	}
	
	if(txtssc.getText().equals(""))
	{
	    jLabel50.setText("Error : SSC Marks not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	    
	}
	else if(txthsc.getText().equals(""))
	{
	    jLabel50.setText("Error : HSC/Diploma Marks not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	else if(!chkdip.isSelected())
	{
	    if(txtfe1.getText().equals(""))
	    {
		jLabel50.setText("Error : FE SEM I Marks not entered");
		jDialog1.repaint();
		jDialog1.setVisible(true);
		return;
	    }
	    
	    else if(txtfe2.getText().equals(""))
	    {
		jLabel50.setText("Error : FE SEM II Marks not entered");
		jDialog1.repaint();
		jDialog1.setVisible(true);
		return;
	    }
	}
	
	else if(txtse1.getText().equals(""))
	{
	    jLabel50.setText("Error : SE SEM I Marks not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	else if(txtse2.getText().equals(""))
	{
	    jLabel50.setText("Error : SE SEM II Marks not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	else if(txtte1.getText().equals(""))
	{
	    avg+=Float.valueOf(txtse2.getText());
	    
	    jLabel50.setText("Error : TE SEM I Marks not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	else if(!chkhsc.isSelected() && !chkdip.isSelected())
	{
	    jLabel50.setText("Error : DIPLOMA OR HSC not entered");
	    jDialog1.repaint();
	    jDialog1.setVisible(true);
	    return;
	}
	
	String dob;
	String month[]={"JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"};
	dob=txtdate.getSelectedItem().toString()+"/"+month[Integer.parseInt(txtmonth.getSelectedItem().toString())-1]+"/"+txtyear.getSelectedItem().toString();
	
	
	String query1,query2,query3;
	int chkvar,chkktvar,hscordip=0,i=0;
	if(chkcomp.isSelected())
	    chkvar=1;
	else
	    chkvar=0;
	
	if(chkhsc.isSelected())
	    hscordip=0;
	if(chkdip.isSelected())
	    hscordip=1;
	
	if(laddr.getText().equals(""))
	{
	    laddr.setText(paddr.getText());
	    
	}
	if(lph.getText().equals(""))
	{
	    lph.setText(pph.getText());
	}
	
	if(chkdip.isSelected() && (txtfe1.getText().equals("") || txtfe2.getText().equals("")))
	{
	    txtfe1.setText("0");
	    txtfe2.setText("0");
	}
	if(txtte2.getText().equals(""))
	    txtte2.setText("0");
	if(txtbe1.getText().equals(""))
	    txtbe1.setText("0");
	if(txtbe2.getText().equals(""))
	    txtbe2.setText("0");
	if(txtproj.getText().equals(""))
	    txtproj.setText("NIL");
	if(ext_acad.getText().equals(""))
	    ext_acad.setText("NIL");
	if(ext_curr.getText().equals(""))
	    ext_curr.setText("NIL");
	
	//************RULES FOR CALCULTING AVERAGE
	//CURRENT RULE IS
	//IF DIPLOMA AND FE MARKS ARE ENTERED ONLY FE MARKS ARE CONSIDERED IGNORING
	//DIPLOMA OTHERWISE DIPLOMA AND SE ONWARDS ARE CONSIDERED
	//IF HSC IS SELECTED IMPLYING DIPLOMA IS NOT SELECTED FE ONWARDS MARKS
	//ARE CONSIDERED
	if(!chkdip.isSelected())
	{
	    avg=Float.valueOf(txtfe1.getText());
	    avg+=Float.valueOf(txtfe2.getText());
	    TotSems=2;
	}
	else
	{
	    if(txtfe1.getText().equals("0"))
	    {
		avg=Float.valueOf(txthsc.getText());
		TotSems=1;
	    }
	    else
	    {
		avg=Float.valueOf(txtfe1.getText());
		avg+=Float.valueOf(txtfe2.getText());
		TotSems=2;
	    }
	}
	
	avg+=Float.valueOf(txtse1.getText());
	avg+=Float.valueOf(txtse2.getText());
	avg+=Float.valueOf(txtte1.getText());
	TotSems+=3;
	
	if(!txtte2.getText().equals("0"))
	{
	    avg+=Float.valueOf(txtte2.getText());
	    TotSems++;
	    
	    if(!txtbe1.getText().equals("0"))
	    {
		avg+=Float.valueOf(txtbe1.getText());
		TotSems++;
		
		if(!txtbe2.getText().equals("0"))
		{
		    avg+=Float.valueOf(txtbe2.getText());
		    TotSems++;
		}
	    }
	}
	
	avg/=TotSems;
	
	query1="insert into stud_per values('" + RollNo + "','" + ((String)sesscmb.getSelectedItem()).charAt(2) + ((String)sesscmb.getSelectedItem()).charAt(3) + ((String)sesscmb.getSelectedItem()).charAt(5) + ((String)sesscmb.getSelectedItem()).charAt(6) + "','" + fname.getText() + "','" + mname.getText() + "','" + lname.getText() + "','" + laddr.getText() + "','" + lph.getText() + "','" + paddr.getText() + "','" + pph.getText() + "','" + mail.getText() +  "','" + dob + "','" + txtcomp.getText()+"',"+ chkvar +")";
	if (chkkt.isSelected())
	    chkktvar=1;
	else
	    chkktvar=0;
	
	
	query2="insert into stud_acad values('" + RollNo + "','" + ((String)sesscmb.getSelectedItem()).charAt(2) + ((String)sesscmb.getSelectedItem()).charAt(3) + ((String)sesscmb.getSelectedItem()).charAt(5) + ((String)sesscmb.getSelectedItem()).charAt(6) + "'," + txtssc.getText() + "," + txthsc.getText() + "," + txtfe1.getText() + "," + txtfe2.getText() + "," + txtse1.getText() + "," + txtse2.getText() + "," + txtte1.getText() + "," + txtte2.getText()  + "," + txtbe1.getText() + "," + txtbe2.getText() + "," + hscordip + "," + Float.toString(avg) + "," + chkktvar +  ")";
	
	query3="insert into stud_extra values('" + RollNo + "','" + ((String)sesscmb.getSelectedItem()).charAt(2) + ((String)sesscmb.getSelectedItem()).charAt(3) + ((String)sesscmb.getSelectedItem()).charAt(5) + ((String)sesscmb.getSelectedItem()).charAt(6) + "','" + txtproj.getText() + "','" + ext_acad.getText() + "','" + ext_curr.getText() + "')";
	
	String DelQuery = "delete:" + RollNo + ":" + ((String)sesscmb.getSelectedItem()).charAt(2) + ((String)sesscmb.getSelectedItem()).charAt(3) + ((String)sesscmb.getSelectedItem()).charAt(5) + ((String)sesscmb.getSelectedItem()).charAt(6) ;
        
        System.out.println(query1);
	System.out.println(query2);
	System.out.println(query3);
	System.out.println(DelQuery);	
	
	try
	{
            int KeySize=5;
            
            char []QueryToSend = EncryptString(DelQuery,KeySize);
	    System.out.println(QueryToSend);
	    out.println(QueryToSend);
            
	    QueryToSend = EncryptString("insert:1:" + query1,KeySize);
	    System.out.println(QueryToSend);
	    out.println(QueryToSend);
            
	    QueryToSend = EncryptString("insert:2:" + query2,KeySize);
	    System.out.println(QueryToSend);
	    out.println(QueryToSend);
            
	    QueryToSend = EncryptString("insert:3:" + query3,KeySize);
	    System.out.println(QueryToSend);
	    out.println(QueryToSend);
            
	    String Ack = in.readLine();
            if(Ack.compareToIgnoreCase("true") == 0)
            {
                JOptionPane.showConfirmDialog(null,"Your record has been successfully inserted",
                        "Success",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE);
                reset();
            }
            else
            {
                JOptionPane.showConfirmDialog(null,"Error in inserting record.\nPlease make sure that : " +
                        "\n1. The record does not exist\n2. No illegal entries have been made.","Error",
                        JOptionPane.DEFAULT_OPTION,JOptionPane.ERROR_MESSAGE);
            }
	}
	catch(Exception e)
	{
	    System.out.println(e);
	    out.println(Boolean.toString(false));
	}
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void CopyFunction(String UpdateRollNo,String UpdateSess)
    {
	char[] roll_array;
	String Branch,Div,RollNo;	
		
	String Received;
	try
	{
	    Received = in.readLine();
	    
	    if(Received.equals("false"))
	    {
		JOptionPane.showMessageDialog(null,"Record does not exist.","Error",JOptionPane.ERROR_MESSAGE);
		return;
	    }
	    
	    fname.setText(Received);
	    mname.setText(in.readLine());
	    lname.setText(in.readLine());
	    laddr.setText(in.readLine());
	    lph.setText(in.readLine());
	    paddr.setText(in.readLine());
	    pph.setText(in.readLine());
	    mail.setText(in.readLine());
	    
	    if(mname.getText().equals("null"))
		mname.setText("");
	    
	    String CompleteDate=in.readLine(),Date,Month,Year;
	    
	    Date=CompleteDate.substring(8,10);
	    txtdate.setSelectedIndex(Integer.parseInt(Date)-1);
	    
	    Month=CompleteDate.substring(5,7);
	    txtmonth.setSelectedIndex(Integer.parseInt(Month)-1);
	    
	    Year=CompleteDate.substring(0,4);
	    txtyear.setSelectedIndex(Integer.parseInt(Year)-1975);
	    
	    txtcomp.setText(in.readLine());
	    
	    if(Integer.parseInt(in.readLine())==0)
	    {
		chkcomp.setSelected(false);
		txtcomp.setText("");
	    }
	    else
	    {
		chkcomp.setSelected(true);
		txtcomp.setEnabled(true);
	    }
		    
	    txtssc.setText(in.readLine());
	    txthsc.setText(in.readLine());
	    txtfe1.setText(in.readLine());
	    txtfe2.setText(in.readLine());
	    txtse1.setText(in.readLine());
	    txtse2.setText(in.readLine());
	    txtte1.setText(in.readLine());
	    txtte2.setText(in.readLine());
	    txtbe1.setText(in.readLine());
	    txtbe2.setText(in.readLine());
	    
	    if(Integer.parseInt(in.readLine()) == 0)
	    {
		chkhsc.setSelected(true);
		chkdip.setSelected(false);
	    }
	    else
	    {
		chkhsc.setSelected(false);
		chkdip.setSelected(true);
	    }
	    
	    in.readLine();
	    
	    if(Integer.parseInt(in.readLine()) ==0)
		chkkt.setSelected(false);
	    else
		chkkt.setSelected(true);
	    
	    txtproj.setText(in.readLine());
	    ext_acad.setText(in.readLine());
	    ext_curr.setText(in.readLine());
	}
	catch(Exception e)
	{
	    e.printStackTrace();
	    return;
	}
    }

    private char[] EncryptString(String InputString,int KeySize)
    {
        char Input[]=new char[InputString.length()];
        char Output[]=new char[InputString.length()];
        Input=InputString.toCharArray();
            
        for(int z=0;z<InputString.length();z++)
        {
            if((Input[z]>='a'&&Input[z]<='z')||(Input[z]>='A'&&Input[z]<='Z'))
                Output[z]=Encrypt(Input[z],KeySize);
            else
                Output[z]=Input[z];
        }
        
        return Output;
    }
    
    private char Encrypt(char PlainChar,int KeySize)
    {
	int i = 0;
	char Temp = PlainChar;
	for (i = 0; i < KeySize; i++)
	{
	    if (Temp == 'z' || Temp == 'Z')
	    {
		switch (Temp)
		{
		    case 'z':
			Temp = 'a';
			break;
		    case 'Z':
			Temp = 'A';
			break;
		}
	    }
	    else
		Temp++;
	    
	}
	
	return Temp;
	
    }
    
    private void txtsscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsscActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_txtsscActionPerformed
    
    private void chkcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkcompActionPerformed
// TODO add your handling code here:
	if(chkcomp.isSelected())
	    txtcomp.setEnabled(true);
	else
	    txtcomp.setEnabled(false);
    }//GEN-LAST:event_chkcompActionPerformed
    
    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
// TODO add your handling code here:
	//emailflag=mail.getText();
    }//GEN-LAST:event_mailFocusLost
    
    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
// TODO add your handling code here:
	//emailflag=null;
    }//GEN-LAST:event_mailFocusGained
    
    private void lphFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lphFocusLost
// TODO add your handling code here:
//          lphflag=lph.getText();
    }//GEN-LAST:event_lphFocusLost
    
    private void lphFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lphFocusGained
// TODO add your handling code here:
	//      lphflag=null;
    }//GEN-LAST:event_lphFocusGained
    
    private void laddrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_laddrFocusLost
// TODO add your handling code here:
	//     laddrflag=laddr.getText();
    }//GEN-LAST:event_laddrFocusLost
    
    private void laddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_laddrFocusGained
// TODO add your handling code here:
	// laddrflag=null;
    }//GEN-LAST:event_laddrFocusGained
    
    private void pphFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pphFocusLost
// TODO add your handling code here:
	//pphflag=pph.getText();
    }//GEN-LAST:event_pphFocusLost
    
    private void pphFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pphFocusGained
// TODO add your handling code here:
	//   pphflag=null;
    }//GEN-LAST:event_pphFocusGained
    
    private void paddrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paddrFocusLost
// TODO add your handling code here:
	//    paddrflag=paddr.getText();
    }//GEN-LAST:event_paddrFocusLost
    
    private void paddrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paddrFocusGained
// TODO add your handling code here:
	//  paddrflag=null;
    }//GEN-LAST:event_paddrFocusGained
    
    private void mnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnameFocusLost
// TODO add your handling code here:
	//   mflag=mname.getText();
    }//GEN-LAST:event_mnameFocusLost
    
    private void mnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnameFocusGained
// TODO add your handling code here:
	//  mflag=null;
    }//GEN-LAST:event_mnameFocusGained
    
    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
// TODO add your handling code here:
	//lflag=lname.getText();
    }//GEN-LAST:event_lnameFocusLost
    
    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
// TODO add your handling code here:
	//    lflag=null;
    }//GEN-LAST:event_lnameFocusGained
    
    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
// TODO add your handling code here:
	//String temp;
	//fflag=fname.getText();
    }//GEN-LAST:event_fnameFocusLost
    
    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
// TODO add your handling code here:
	//fflag=null;
    }//GEN-LAST:event_fnameFocusGained
    
    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed
    
    private void roll_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roll_noFocusLost
// rollflag=roll_no.getText();
    }//GEN-LAST:event_roll_noFocusLost
    
    private void roll_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roll_noFocusGained
// TODO add your handling code here:
	
	// rollflag=null;
    }//GEN-LAST:event_roll_noFocusGained
    
    private void comboclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboclassActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_comboclassActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new Stud_Client();
		
	    }
	});
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JPanel AcademicsInsert;
    private javax.swing.JButton Display;
    private javax.swing.JMenuItem DisplayMenuItem;
    private javax.swing.JPanel ExtraInsert;
    private javax.swing.JMenu Help;
    private javax.swing.JTextField IPaddr;
    private javax.swing.JMenuItem InsertMenuItem;
    private javax.swing.JPanel InsertPanel;
    private javax.swing.JPanel PersonalInsert;
    private javax.swing.JMenuItem RefreshMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkcomp;
    private javax.swing.JRadioButton chkdip;
    private javax.swing.JRadioButton chkhsc;
    private javax.swing.JCheckBox chkkt;
    private javax.swing.JComboBox combobranch;
    private javax.swing.JComboBox comboclass;
    private javax.swing.JComboBox combodiv;
    private javax.swing.JTextArea ext_acad;
    private javax.swing.JTextArea ext_curr;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea laddr;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField lph;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mname;
    private javax.swing.JTextArea paddr;
    private javax.swing.JTextField pph;
    private javax.swing.JTextField roll_no;
    private javax.swing.JComboBox sesscmb;
    private javax.swing.JTextField txtbe1;
    private javax.swing.JTextField txtbe2;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JComboBox txtdate;
    private javax.swing.JTextField txtfe1;
    private javax.swing.JTextField txtfe2;
    private javax.swing.JTextField txthsc;
    private javax.swing.JComboBox txtmonth;
    private javax.swing.JTextArea txtproj;
    private javax.swing.JTextField txtse1;
    private javax.swing.JTextField txtse2;
    private javax.swing.JTextField txtssc;
    private javax.swing.JTextField txtte1;
    private javax.swing.JTextField txtte2;
    private javax.swing.JComboBox txtyear;
    // End of variables declaration//GEN-END:variables
    
}
