/*
 * Server_op.java
 *
 * Created on July 27, 2006, 5:19 PM
 */

package plcmnt_server;

/**
 *
 * @author  user
 */
public class Server_op extends javax.swing.JDialog {
    
    /** Creates new form Server_op */
    public Server_op(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
    }
    
    public Server_op(String RollNum) {        
        initComponents();
        //this.setAlwaysOnTop(true);
        RcdAdd.setText("Roll No. : " + RollNum + " added.");
        this.setSize(RcdAdd.getPreferredSize().width + 20,RcdAdd.getPreferredSize().height + 10);        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        RcdAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server Output");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setUndecorated(true);
        RcdAdd.setFont(new java.awt.Font("Tahoma", 0, 18));
        RcdAdd.setText("Record Added");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(RcdAdd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(RcdAdd)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setBounds(869, 703, 170, 74);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_op(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RcdAdd;
    // End of variables declaration//GEN-END:variables
    
}
